library(shiny)

shinyUI(
     fluidPage(
         titlePanel("Coursera Data Science Capstone - David Rothall (March 28th, 2017, updated Aug 16, 2017)"),
             sidebarLayout(
                 sidebarPanel(
                     radioButtons("variable", "Prediction Type",
                                  c("Predict Next Word" = " ",
                                    "Autocomplete Word" = ""),
                                  selected = " ",
                                  inline = FALSE,
                                  width = NULL),
                     hr(),
                     textInput("phrase", "Enter an English Phrase Here"),
                     hr(),
                     textOutput("predictions"),
                     hr(),
                     tableOutput("predTable")
                 ),
                 
                 mainPanel(
                     tabsetPanel(type = "tabs", 
                                 tabPanel("Information",
                                          h3("Word Prediction and Autocompletion"),
                                          p("This app will either predict the next word in a phrase or ",
                                            "autocomplete the current word. Try it out!"
                                            ),
                                          br(),
                                          p("Try choosing a single word, type a second word from the ",
                                            "given predictions, and another, and another... and see what ",
                                            "phrases you end with!"),
                                          br(),
                                          p("Notes:"),
                                          tags$ul(
                                              tags$li("Please wait a few seconds for the page to load."),
                                              tags$li("Any questions feel free to visit my ",
                                                      a("LinkedIn profile", href= "https://www.linkedin.com/in/davidrothall/"),
                                                      " or contact me at david.rothall@gmail.com"),
                                              tags$li("Any projects I'm working on can be found on ",
                                                a("GitHub!", href="https://github.com/the-roth"))
                                          )
                                 ),
                                 tabPanel("Documentation", 
                                          h3("Project Description"),
                                          p("This app was designed as part of the Capstone project for ",
                                            "the Data Science specialisation ",
                                            "on the Coursera website. It contains 10 courses ",
                                            "which were very interesting and engaging ",
                                            "and I'd recommend anyone considering learning Data Science ",
                                            "to study it."),
                                          p("Submitted for the Capstone was a Shiny app that predicts ",
                                            "the next word in a phrase along with a ",
                                            a("5 slide presentation ", href="http://rpubs.com/the_roth/CourseraCapstonePitch"),
                                            "highlighting its features. ",
                                            a("The dataset", href="https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip"),
                                            "is from a corpus called ",
                                            a("HC Corpora", href="www.corpora.heliohost.org"),
                                            " which also contains a ",
                                            a("readme file", href="http://www.corpora.heliohost.org/aboutcorpus.html"),
                                            " for details. A sample from these (millions of) news articles, blogs ",
                                            "and Twitter posts is ",
                                            "taken as to cover as much of the English language as possible."
                                          ),
                                          h3("Extracting phrases from the dataset"),
                                          p("The sample dataset used contained roughly 6% of all blogs, news ",
                                            "and Twitter articles in the given corpus, 240000 articles in total. ",
                                            "The punctuation in the sample as well as numbers and any ",
                                            "undesired phrases (e.g. some profanity) ",
                                            "was then removed as to properly extract all words later. ",
                                            "All uni- bi- tri- and quadgrams appearing more than once in the ",
                                            "sample dataset were then extracted. ",
                                            "Please see the Improvements section for further details."
                                          ),
                                          h3("Prediction Model / Algorithm"),
                                          p("The user enters a phrase of any length, with the last 3 words being ",
                                            "extracted from the ",
                                            "phrase (fewer if the phrase is shorter). If the user checks the ",
                                            "'Predict Next Word' box, ",
                                            "the model will return the last word of any quadgrams found ",
                                            "in the sample dataset, in order of maximum likelihood.",
                                            "If the 'Autocomplete Word' box is checked, the model ",
                                            "will instead extract the last words of any trigrams in the sample ",
                                            "dataset, which then acts to autocomplete the last word in the given phrase."
                                            ),
                                          p("If less than 5 results are found in the above process then the model will ",
                                            "then consider the last 2 words of the phrase and search for results in the ",
                                            "trigram and bigram list respectively depending on the mode of ",
                                            "prediction. ",
                                            "This process if then repeated for the last phrase in the word ",
                                            "if no results are found (using bigram/unigram data). ",
                                            "If no predictions are found at all the app will tell the user ",
                                            "to try another phrase."
                                            )
                                 ),
                                 tabPanel("Notes / Improvements",
                                          h3("Algorithm speed"),
                                          p("The search algorithm originally used the grep function, which took ",
                                            "up to 400 milliseconds depending on how many n-gram sets it needed to search. ",
                                            "Using the startswith() function the model was reduced to 35ms. ",
                                            "This can be improved with faster lookups but I'm not sure how to ",
                                            "quickly filter data tables by keys; grep still takes way too long here."),
                                          h3("Improving Prediction Accuracy"),
                                          p("The model joins maximum likelihood estimates prioritising from the ",
                                            "quadgram set first followed by trigrams, bigrams then unigrams, so ",
                                            "if the top 5 predictions need to be created from multiple n-gram ",
                                            "lists they will do so in that order. Future modeling would include ",
                                            "implementing Katz's Backoff model which is similar but allows for a ",
                                            "few extra parameters in choosing the relative strengths of higher ",
                                            "n-gram likelihoods compared to backoff probabilities of (n-1)-grams.",
                                            "Current prediction accuracy is 21, 27 and 29% for the top 1, 3 and 5 ",
                                            "word predictions respectively, using testing data from news, blogs ",
                                            "and Twitter datasets."),
                                          h3("Improving Grammar"),
                                          p("Some styles of writing are missed in news articles, blogs and Twitter ",
                                            "posts. Prediction accuracy for phrases geared towards actual flows of ",
                                            "conversation are likely to be reduced as the phrasing will be ",
                                            "slightly different. Future attempts to cover the English language ",
                                            "could include those from either books or interviews as opposed to ",
                                            "simply relaying information from the writer to the reader."),

                                          h3("Model Size / Usability"),
                                          p("The model size is relatively small (5MB zipped / 20MB ",
                                            "unzipped) and so it loads quickly, at least for one user. ",
                                            "As R is a single threaded application, the Shiny app ",
                                            "can only handle one user's request at a time. Thus it can handle ",
                                            "1000/35 ~ 30 requests / second minus any extra work the Shiny app ",
                                            "itself needs to do. The memory usage according to the ",
                                            "Shiny dashboard is around 60MB per user if they try 10 - 20 phrases. ",
                                            "With the default free 1GB ",
                                            "plan the app can handle up to around 15 concurrent users. ",
                                            "I assume the waiting time would be too high if there were more users.")
                                 )
                     )
                 )
             )
         )
)